### PR TITLE
Updated phpgt/dom to the last version 2.2.3

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

In this PR updated `phpgt/dom` to the last version 2.2.3

### Fixed Issues (if relevant)

1. magento/magento2#34633

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by xmav** [comment]
Test builds with a new library version is in progress

**Review by andrewbess — APPROVED** [review]

**Comment by xmav** [comment]
@magento import code to magento-trigger/magento2-page-builder

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `magento-trigger/magento2-page-builder` repository. Branch name: `imported-anzin-magento2-page-builder-794`.

**Comment by xmav** [comment]
@magento import code to magento-trigger/magento2-page-builder

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `magento-trigger/magento2-page-builder` repository. Branch name: `imported-anzin-magento2-page-builder-794`.

**Pull request merged**
