### PR TITLE
Alt text for Images, Banners and Slides for better accessibility and SEO

### LINKED ISSUE #746: Alt text for Images
h1. Story

As a marketer I want to set alt text to images (image, banner, slide) *so that* content I create with PageBuilder has better accessibility and SEO 

h2. Business Value
make PageBuilder content accessible and SEO optimized

AC:
- SEO(alt and title) block should be available for Slider and Banner PB entity
- instead of `ALT` attribute should be used [`aria-label`](https://www.aditus.io/aria/aria-label/)

Testing notes:
- need to be sure that `aria-label` works as `alt` attribute. Can be read by a screen reader
Possible tools:
- https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn
- https://chrome.google.com/webstore/detail/images-onoff/nfmlhilnjccdggifdbhnhkffmjgalbgg

### PR DESCRIPTION
**Pull request by manavluhar**
### Description (*)
* SEO Fieldset in Page Builder **Image / Banner / Slide**
seo-fieldset-in-page-builder-form
*  Banner SEO in frontend
banner-seo-proof

* Slider SEO in Frontend
slide-seo-proof

* Image is already having SEO functionality

### Story

* [746](https://jira.corp.magento.com/browse/746) Alt text for Images

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#746: Alt text for Images

### Manual testing scenarios (*)
* By going inside `Admin Panel -> CONTENT -> Pages -> Edit Home page` open Content section and click on **Edit with Page Builder** button.
 * Add New Banner/Add New Slider **->** Hover on the Banner Area / Edit Slide **->** Click On ⚙️[Edit] Here admin can find **Search Engin Optimization** Fieldset.
 * Inside **Search Engin Optimization** Fieldset **Alternative Text** and **Title Attribute** fields will be there.
 * After filling required fields, One can check by going to the `Storefront -> Home page`  and inspect **Banner / Slide / Image** and check that Alternative Text and Title Attribute will be there which makes PageBuilder content accessible and SEO optimized 

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by manavluhar** [comment]
@magento run Functional Tests B2B

**Comment by manavluhar** [comment]
@magento run Unit Tests

**Comment by sidolov** [comment]
@magento run Unit Tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@manavluhar changes look good to me. Could you please cover new functionality with MFTF test? (maybe a good idea to find already created tests and edit them to fill new fields and then check them on the  storefront)

**Comment by manavluhar** [comment]
Sure @sidolov will do that! 🙌

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

**Comment by sdzhepa** [comment]
**UPDATE on 11 Nov 2021**

This PR requires additional discussion with PO
- images already have ALT attributes
- adding ALT attribute allowed only to the `<image>` tag, but not for `<div>` https://www.w3schools.com/tags/att_alt.asp







# Admin Side

New Section "Search Engine Optimization" was added to the Banner and Slider PageBuilder content types.
The section contains new fields/settings: "Alternative Text" and " Title Attribute"
- Was tested that these options exist and Admin users can edit them.  
- Was tested these attributes are available(shown) on the Storefront

## Banner
Banner

## Slider(available per each slide)
Slider

# Storefront Side

## Banner
SF_Banner

## Slider(available per each slide)
SF_Slider

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Unit Tests

**Comment by sdzhepa** [comment]
QA Passed after reworking of PR

Were tested next Page Builder entities: Banner, Image, Slider
Were tested when this entity inside Row and Tab "containers" 
- image tag has added `alt` attribute
- for `div` was used [`aria-label`](https://www.aditus.io/aria/aria-label/) instead.

Additional was performed testing using [Screen Reader](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn): All alternative text for all these entities can be read by screen reader 



_**Note**: Looks like implementation is done, only some failed functional tests. Fails look like related to the incorrect locators. So i assume no code changes just fix test. But in case if any code changes will be performed to change implementation/logic pls ping me for one more testing round_

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,WebAPI Tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento2-page-builder

**Comment by m2-github-services** [comment]
@sidolov the Pull Request is successfully imported.

**Pull request merged**
