### PR TITLE
tinyMCE migration 5to7

### PR DESCRIPTION
**Pull request by naoverite**
### Description (*)

In TinyMCE 5, the toolbar font size option is referred to as `fontsizeselect`. However, in TinyMCE 7, this option has been renamed to `fontsize`. This causes compatibility issues when migrating from TinyMCE 5 to TinyMCE 7 as the old toolbar configuration (fontsizeselect) no longer works in the new version.

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
Before this gets processed, maybe the adobe guys can internally check what's going to happen in scope of https://github.com/magento/magento2/issues/39252, it seems like you are going to downgrade TinyMCE again because the license of v7 is in violation with your open source software.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — COMMENTED** [review]
Hello @kadowakiverite,

Thanks for the contribution!

Due to the following issue:

https://github.com/magento/magento2/issues/39252

We are rolling back the version. Once the issue is resolved, we will pick up this PR for further processing. In the meantime, we are moving this PR to `On Hold`.

Thanks again!

**Comment by naoverite** [comment]
Hello @engcom-Hotel,

Thank you for the update!
 I understand the situation and will wait until the issue is resolved.

Best regards

**Comment by hostep** [comment]
Looks like this got fixed in https://github.com/magento/magento2-page-builder/commit/74e34f4c6cf0088a3b30e3bf5c270a1feeb0e0e3, which got [merged today](https://github.com/magento/magento2-page-builder/commit/2c2f7a0eaab0c755dbaef2806d07e41e8d1559cd)

**Comment by engcom-Hotel** [comment]
Thanks @hostep for highlighting the same. We can close this PR.

Thanks @kadowakiverite for the contributions.

**Pull request closed without merging**
