### PR TITLE
Move preference to area where class exists

### PR DESCRIPTION
**Pull request by fredden**
### Description
This preference is defined in XML but the class referenced does not exist. The class does exist in the adminhtml area, so I've moved the preference there. This is blocking progress on https://github.com/magento/magento2/pull/33161

### Story
*None*

### Bug
*None*

### Task
*None*

### Fixed Issues (if relevant)
*None*

### Builds
*Unknown*

### Related Pull Requests
https://github.com/magento/magento2/pull/33161

### Manual testing scenarios
No visible changes should be apparent with this change.

### Questions or comments
*None*

### Checklist
- [x] Pull request has a meaningful description of its purpose
- [x] All commits are accompanied by meaningful commit messages
- [x] All new or changed code is covered with unit/integration tests (if applicable)
- [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Moving this PR `On Hold` as we are not able to run the tests on this PR. Currently, there is a ongoing JIRA to resolve this issue:

 https://jira.corp.adobe.com/browse/ACPLTSRV-4253

**Comment by fredden** [comment]
@magento run all tests

as requested via Slack by @engcom-Hotel.

**Comment by engcom-Hotel** [comment]
As we are unable to run the automated tests on this PR, we have created a new PR to preserve the commits of this PR:

https://github.com/magento-commerce/magento2-page-builder/pull/304

Hence closing this PR.

**Comment by hostep** [comment]
Looks like it got merged after all (finally): https://github.com/magento/magento2-page-builder/compare/6dd003ed5b...bdc2e1a447

**Pull request closed without merging**
