### PR TITLE
Column group story

### LINKED ISSUE #595: User duplicates/hides/deletes Column group
As a Marketer I want to duplicate, hide and delete Columns **so that** I can manipulate Column group the same way as other content types and have unified experience

**Preconditions**
* User is logged into Admin Panel
* User is on a page that has Page Builder
* User has Column group on Stage

**Acceptance Criteria**
* User accesses Column group option panel and sees options to duplicate, hide and delete Column group
* User can delete Column group and see all the content inside the Column group deleted. Confirmation message displayed.
* User can delete columns from the Column group except last one. If user wants to delete the last column, the entire group should be deleted PB-1174
  * "trash" icon shown as inactive for the last one column(children) user can click remove only whole Column Group
* User can duplicate Column group with all the content that is inside and see the duplicated Column group appeared under the original Column group.
* User can hide Column group with all the content that is inside, see them blocked from editing on stage and not visible on storefront

### LINKED ISSUE #747: User can delete columns from the column group except the last one
User can delete columns from the column group except the last one. To delete the last one, user delete a Column group

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>

Verify that last column item can not be deleted from column group (delete button gets disabled similar to last row on page)
* < > Verify that column group can still be deleted in this state (just not column item)

### LINKED ISSUE #748: Configure rules for columns
User can add only Columns to Column group (only columns can extend column group). Make sure rules properly configured

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>
* < > Verify that you cannot move any other content type from left panel or from stage into column group other than Columns
  * < > Verify no drop indicators for any content type in Column Group
  * < > Verify that dropping other content types into Column Group will not throw a console error
  * < > Dragging & dropping Columns from left panel into existing column group will add another column to the area that you dropped it. This column will get added as the smallest size column allowed by the grid size
  * < > Dragging & dropping a column from another column group to a column group will add the column & its inner contents. This column will get added as the smallest size column allowed by the grid size

### LINKED ISSUE #749: User can move Column group on Stage
User can move Column group on Stage and have all the columns with content inside moved to the new place.

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>
* < > Verify can move column group
  * < > Verify that all child content types are moved as well
  * < > Verify that saving page after move will save column group in new location
  * < > Verify can only move to a row or a tab item
    * < > Check cannot move to all other content types
      * < > Verify cannot move into another column group or column item

### LINKED ISSUE #750: Introduce min height setting for Columns
User can add a min height to the Column group to set a min container height.
 Clarify with PO: should it be unique for mobile and desktop?

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>
* < > Verify editing Minimum Height works as expected
  * < > Check that min height defines the min height of all columns in the group unless the min height on individual column was redefined by user
    * < > Check admin & storefront
  * < > Verify min height accepts different value inputs & renders correctly
    * < > 0px
    * < > empty
    * < > doesnt allow negative values
    * < > allows things like 100vh, calculations, etc

### LINKED ISSUE #751: Move grid size setting to settings panel
User can specify grid size for each column group in scope of settings panel.
 Grid size control (3 dots) is removed from columns component.

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>

< > Verify can edit column group
* < > Verify editing Grid Size works as expected
  * < > Verify that changing grid size value to a number greater than the current number of columns will update the column sizes to fill whole column group (& update the column labels with the new max value)
  * < > Verify that changing grid size value to a number less than the current number of columns will resize columns w/ content, delete empty columns, and **NOT** delete columns with content (& update the column labels with the new max value)
  * < > Verify that repeatedly changing grid size value will **NEVER** result in the columns not filling the entire column group nor flowing outside of the column group
  * < > Verify that changing `Default Column Grid Size` at `Store > Configuration > General > Content Management > Advanced Content Tools`) changes the default value shown in the `Grid Size` field for new column groups
  * < > Verify that changing `Default Column Grid Size` at `Store > Configuration > General > Content Management > Advanced Content Tools`) does **NOT** change the grid size of existing column groups (it only changes the default value on the edit form for new column groups)
  * < > Verify field validation errors occur on Grid Size field after entering below values & clicking Save on the edit form
    * < > Cannot enter non-numeric values
      * < > Error message: `Please enter a valid number.`
    * < > Cannot enter 0, 1, negative numbers
      * < > Error message: `The minimum grid size supported is 2.`
    * < > Cannot enter numbers greater than `Maximum Column Grid Size` (found at `Store > Configuration > General > Content Management > Advanced Content Tools`)
      * < > Error message: `The maximum grid size supported is 16.` (where 16 is whatever value you have set for the store configuration)
    * < > Cannot enter numbers less than the total amount of current columns with content in the column group (ex: have 3 columns with content, change value to 2)
      * < > Error message: `Grid size cannot be smaller than the current total amount of columns, minus any empty columns`
    * < > Verify that `Grid Size` field has tooltip next to field w/ on-hover tooltip text: `Grid size determines the maximum number of columns available. Select a value between 2 and 16` (where 16 is whatever value you have set for the store configuration)
  * < > Verify that changing `Maximum Column Grid Size` (found at `Store > Configuration > General > Content Management > Advanced Content Tools`) affects the maximum value you can set for a column group grid size on the edit form & updates the field validation messages above & updates the tooltip message
    * < > Verify that changing `Maximum Column Grid Size` at `Store > Configuration > General > Content Management > Advanced Content Tools`) does **NOT** change the grid size of existing column groups

### LINKED ISSUE #752: Introduce settings panel form Columns
**User opens Columns settings and sees groups**
 - Background
 - Advanced Settings

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>

 

**Verify default attributes for each column group attribute**
* < > General section
  * < > No section title
  * < > Grid Size: 12
    * < > Equal to the value in `Default Column Grid Size` at `Store > Configuration > General > Content Management > Advanced Content Tools`)
  * < > Minimum Height: empty
* < > Background section (verify matches column content type defaults)
  * < > section title: `Background`
  * < > Background Color: empty color swatch, No Color placeholder text
  * < > Background Image: empty
  * < > Background Mobile Image: empty
  * < > Background Size: Cover
  * < > Background Position: Top Left
  * < > Background Attachment: Scroll
  * < > Background Repeat: No
* < > Advanced Configuration section (verify matches column content type defaults)
  * < > section title: `Advanced`
  * < > Alignment: Default
  * < > Border: None
  * < > Border Color: empty color swatch, No Color placeholder text (& disabled)
  * < > Border Width: 1 (& disabled)
  * < > Border Radius: 0
  * < > CSS Classes: empty
  * < > Margins: 0 (for all)
  * < > Padding: 10 (for all)

### LINKED ISSUE #753: Introduce action panel for Columns
User sees action panel available for Columns where only move handle, Label and Settings present.

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>

### LINKED ISSUE #754: Introduce Columns groups
The user drops Column group on Stage and sees Columns content type with 2 Columns inside.

Verify content type matches mockups (on stage & edit panel): <https://xd.adobe.com/view/8f4b36be-211c-4956-9956-b0457fa9b616-da18/screen/8762947b-1b90-4f4d-9b77-19de906eb0c8/>

### PR DESCRIPTION
**Pull request by paras89**
### Fixed Issues (if relevant)

1. Fixes magento/magento2-page-builder#754: Introduce Column Groups
2. Fixes magento/magento2-page-builder#749: User can move Column Group on stage
3. Fixes magento/magento2-page-builder#748: Configure rules for columns
4. Fixes magento/magento2-page-builder#747: User can delete columns from the column group except the last one
5. Fixes magento/magento2-page-builder#751: Move grid size setting to settings panel 
6. Fixes magento/magento2-page-builder#753: Introduce action panel for Columns
7. Fixes magento/magento2-page-builder#752 Introduce settings panel form Columns
8. Fixes magento/magento2-page-builder#750 Introduce min height setting for Columns
9.  Fixes magento/magento2-page-builder#595 User duplicates/hides/deletes Column group
### Related Pull Requests
https://github.com/magento/magento2/pull/34804

### Manual testing scenarios (*)

1. ...
2. ...

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sdzhepa** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all testts

**Comment by paras89** [comment]
@mgento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magentot run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run Functional Tests CE

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Pull request merged**
