### PR TITLE
Remove maxlength limit for URL Links in page builder.

### LINKED ISSUE #770: Page builder links with additional parameter
One of the bigger problems for the editor in the admin area is that the links unfortunately do not match again and again. 

The main problem is when creating links that require a direct parameter or anchors, this can be done by Magento only a link with its own URL:
image

Basically there is the problem that the link does not run anymore when the URL is changed.
Here the simplest solution would be to insert an additional field:
image
Ashampoo_Snap_Montag, 23  August 2021_09h01m59s_028_
Ashampoo_Snap_Montag, 23  August 2021_09h04m12s_029_

This would have the advantage that the reason URL is always correct

### PR DESCRIPTION
**Pull request by Bashev**
### Description (*)
URL Links used by page builder not need to be limited to 255 signs.

### Story
When we creating banners, sliders, adding images or just make a links via page builder we can choose different type of links - URL, Pages, Products or Categories. Based on database limitation url-link in magento is limited to 255 signs, but this is not related to page builder because we store url in the html of the page and limit is not applicable. 

This pull request remove limitation for URLs (internal or external links) which can be added to most of page builder components.

### Fixed Issues (if relevant)

1. Can help for Feature Request or resolves #770 magento/magento2-page-builder

### Manual testing scenarios (*)
1. Go to Pages.
2. Add new Page
3. Add content with Page Builder
4. Add New Row
5. Insert Image Component 
6. Add URL Link (this example is 333 symbols): /kuche/hrana-za-kucheta?age%5B0%5D=%D0%97%D1%80%D1%8F%D0%BB%D0%B0+%D0%B2%D1%8A%D0%B7%D1%80%D0%B0%D1%81%D1%82&age%5B1%5D=%D0%9D%D0%B0%D0%BF%D1%80%D0%B5%D0%B4%D0%BD%D0%B0%D0%BB%D0%B0+%D0%B2%D1%8A%D0%B7%D1%80%D0%B0%D1%81%D1%82&manufacturer=Hill%27s&price=5-40&size_dog=%D0%9C%D0%BD%D0%BE%D0%B3%D0%BE+%D0%BC%D0%B0%D0%BB%D0%BA%D0%BE
7. Save

Without this modification url will be cropped and will break the result.

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run Tests B2B

**Comment by Bashev** [comment]
@magento run Tests B2B

**Comment by Bashev** [comment]
@magento run functional tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run WebAPI tests

**Comment by paras89** [comment]
@Bashev Can you pull develop branch into your fork's branch and re-reun the tests? We can then process this PR. thanks!

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run Static Tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by Bashev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by Bashev** [comment]
@magento run Functional Tests EE

**Pull request merged**
