### PR TITLE
Add YouTube NoCookie Support

### PR DESCRIPTION
**Pull request by sprankhub**
### Description (*)
Adds support for youtube-nocookie.com domain.

### Bug
#826

### Fixed Issues (if relevant)
1. magento/magento2-page-builder#826: YouTube Nocookie URL Not Accepted

### Manual testing scenarios (*)
See magento/magento2-page-builder#826.

### Checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BorisovskiP** [comment]
Tested and can confirm this patch does fix the issue.One thing to note is that in order for the youtube-no-cookie link to be loaded by pagebuilder, the `Maximum Width` must be specified. Otherwise the following error is thrown:

`Temporarily allowed to save HTML value that contains restricted elements. Allowed HTML tags are: div, a, p, span, em, strong, ul, li, ol, h5, h4, h3, h2, h1, table, tbody, tr, td, th, tfoot, img, hr, figure, button, i, u, br, b, iframe, style, pre, svg, animate, animateMotion, animateTransform, circle, clipPath, defs, desc, ellipse, feBlend, feColorMatrix, feComponentTransfer, feComposite, feConvolveMatrix, feDiffuseLighting, feDisplacementMap, feDistantLight, feFlood, feFuncA, feFuncB, feFuncG, feFuncR, feGaussianBlur, feImage, feMerge, feMergeNode, feMorphology, feOffset, fePointLight, feSpecularLighting, feSpotLight, feTile, feTurbulence, filter, foreignObject, g, image, line, linearGradient, marker, mask, metadata, mpath, path, pattern, polygon, polyline, radialGradient, rect, set, stop, switch, symbol, text, textPath, title, tspan, use, view`

**Comment by sprankhub** [comment]
Hmm indeed, unfortunately, it is a bit more involved than this :-/ I will try to work on a proper fix.

**Comment by bluemwhitew** [comment]
Another issue you'll most probably face is that Page Builder will revert back to using `www.youtube.com` when it reads the saved data and pre-populates the Video content type's fields.

For example, both https://www.youtube.com/watch?v=dQw4w9WgXcQ and https://youtu.be/dQw4w9WgXcQ (note the different domains) get converted to https://www.youtube.com/embed/dQw4w9WgXcQ when the data is read, meaning if the content is re-saved - even without changes - it'll go back to using the cookie-based domain.

**Comment by sprankhub** [comment]
With my latest changes, this should now work as expected. Mind testing, @bluemwhitew?

**Comment by paras89** [comment]
@magento run all tests

**Comment by sprankhub** [comment]
@bluemwhitew, mind testing the changes from this PR?

@paras89, I think the failing tests are unrelated to this PR...?

**Comment by sprankhub** [comment]
@paras89, would you be able to have a look at this PR?

**Review by convenient — APPROVED** [review]

**Comment by convenient** [comment]
I mistakenly approved this rather than 👍 , was on autopilot and too used to approving internal Ampersand PRs, whoops 😆

**Comment by bluemwhitew** [comment]
@sprankhub,

I would highly suggest adding (or extending) [Magento Functional Testing Framework](https://developer.adobe.com/commerce/testing/functional-testing-framework) (MFTF) tests to support this changeset, which will make it easier to validate.

**Comment by sprankhub** [comment]
Thanks for the advice, @bluemwhitew. I value my time highly, though. If any Adobe official said "we'll merge this as soon as there is MFTF coverage", I'll consider implementing this. Until then, I save my time for more valuable tasks...

**Comment by sprankhub** [comment]
@sidolov, I feel bad for tagging you directly, but I currently do not know how else I could move this forward. Would you be able to move this forward?

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @sprankhub,

I have reviewed the changes and it looks good to me. Can you please add some automated test for changes made in this PR?

We will move it further with this after the automated test has been added.

Thanks

**Comment by sprankhub** [comment]
@magento run all tests

**Comment by sprankhub** [comment]
@magento run all tests

**Comment by sprankhub** [comment]
@engcom-Hotel, I extended a fitting MFTF test. The failing WebAPI Tests look unrelated to me.

Could you have another look, please?

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
Thanks @sprankhub for adding the automated test. I am approving this PR to process further.

**Comment by bluemwhitew** [comment]
Awesome job on this, @sprankhub! 🤘🏻

**Comment by engcom-Bravo** [comment]
Hi @sprankhub,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Create CMS page.
- Use page builder to add content.
- Add video element. Enter https://www.youtube-nocookie.com/embed/019DMLEVkos as "Video URL".
- Click "Save" button.


**Before:** :heavy_multiplication_x: 


Screenshot 2023-11-24 at 2 16 40 PM







**After:** :heavy_check_mark:  




Screenshot 2023-11-27 at 12 08 34 PM



New-Page-Pages-Elements-Content-Magento-Admin

**Comment by devarul** [comment]
This PR is in development by an internal team, it will be completed and delivered to the mainline according to our standards and processes. All the original community commits will be preserved.

**Comment by engcom-Hotel** [comment]
Thanks @devarul for the updates. We are moving this PR `On Hold` till that time.

**Pull request merged**
