### PR TITLE
fix #537 remove layout definition

### LINKED ISSUE #537: Layout shouldn't be set in a `page_layout` xml file.
### Preconditions (*)
1. Magento Page Builder version >= 1.3.0

### Steps to reproduce (*)
1. Create a `Magento_Catalog/layout/catalaog_category_view.xml` in your theme.
2. Set the attribute `layout` of the xml-node `page` to `1column`

### Expected result (*)
1. Category page has layout one column

### Actual result (*)
1. Category page has layout two columns left

This issue is caused by the file `view/frontend/page_layout/catalog_category_view.xml`. A `page_layout` file should never set a `layout` becasue they are the last loaded layout xml files. This bug overwrites the value for layout set in the theme.

This is the patch that resolves the issue. I don't have a paid GitHub account, so can't create a PR.

```
===================================================================
--- a/view/frontend/page_layout/catalog_category_view.xml	(date 1592218590076)
+++ b/view/frontend/page_layout/catalog_category_view.xml	(date 1592218590076)
@@ -5,7 +5,7 @@
  * See COPYING.txt for license details.
  */
 -->
-<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="2columns-left" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
+<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
     <body>
         <referenceContainer name="category.view.container">
             <referenceBlock name="category.description" template="Magento_PageBuilder::catalog/category/view/description.phtml"/>
```

### PR DESCRIPTION
**Pull request by unailopez16**
### Description (*)

This PR removes the layout definition from Magento\PageBuilder module in category view pages, since it's already defined in Magento\Catalog module, and due to layouts loading order it breaks the ability to apply a custom layout type from a category edit page in backou

### Bug
 [537](https://github.com/magento/magento2-page-builder/issues/537)

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#537: Layout shouldn't be set in a page_layout xml file.

### Manual testing scenarios (*)

1. Install Magento\PageBuilder y a M2.4.3 fresh instance
2. Go to Catalog -> Categories
2. Edit one category
3. Apply a custom layout type in Design Section
4. Layout type is not applied to front page category

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/magento2-page-builder

**Comment by m2-github-services** [comment]
@sidolov the Pull Request is successfully imported.

**Comment by norgeindian** [comment]
In general: Why is this file in the `page_layout` folder?
In my understanding, this folder is only there to create new page layouts. All other files there are used this way, only this one is not and also not mentioned in `layouts.xml`.
May it be, that this needs to be moved to `layout` folder?

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@unailopez16 can you pull develop branch into your fork's branch and push so we can run tests again and get to merge this PR? thanks!

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run Functional Tests B2B,  WebAPI Tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by kanhaiya5590** [comment]
Raised a PR  - https://github.com/magento/magento2-page-builder/pull/835

to fix the fallback mechanism of this file instead of just fixing the content part.

CC :  @norgeindian - https://github.com/magento/magento2-page-builder/pull/782#issuecomment-946544966 given some  addition info :)

**Comment by glo24157** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @unailopez16,

Thanks for the contribution!

:x: QA not Passed

We have tried to reproduce the issue in the latest 2.4-develop branch but it is not reproducible for us. We can see the 1-page layout on the category page in the store view. Please refer to the below screenshot for reference:

image

We have followed the below steps to reproduce the issue:

- Install Magento\PageBuilder in the latest development branch i.e. 2.4-develop
- Go to Catalog -> Categories
- Edit one category
- Apply a custom layout type in the Design Section
image
- Layout type is applied to the front page category

It seems the issue has been fixed in the latest branch. Please try to reproduce the issue and let us know if you are able to reproduce it.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @unailopez16,

As per this comment https://github.com/magento/magento2-page-builder/pull/782#issuecomment-1895371820, we are unable to reproduce the issue in the latest development branch i.e. 2.4-develop.

We are unable to receive a reply from you on this PR, hence we are closing this PR. Please comment here if you still continue with this PR.

Thanks

**Pull request closed without merging**
