### PR TITLE
Community - Width & Height attribute - Pagebuilder image #767

### LINKED ISSUE #867: [Issue] Width & Height attribute - Pagebuilder image #767
This issue is automatically created based on existing pull request: magento/magento2-page-builder#847: Width & Height attribute - Pagebuilder image #767

---------
Width and Height attribute added for Pagebuilder image element 

https://github.com/magento/magento2-page-builder/issues/767

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by aj-prajapati**
Width and Height attribute added for Pagebuilder image element 

https://github.com/magento/magento2-page-builder/issues/767

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#<issue_number>: Issue title

### Related Pull Requests

https://github.com/magento-commerce/magento2-infrastructure/pull/1880

### Manual testing scenarios (*)

1. ...
2. ...

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2-page-builder#867: Width & Height attribute - Pagebuilder image #767

### CODE REVIEW

**Comment by larsmbm** [comment]
Hello @aj-prajapati 

Thanks for making this code. We do use it. Although we did add code for loading attribute as wel. We think it's a good to at it to you merge request.

This is the code we made:

pagebuilder_image_form.xml
`        <field name="image_attribute_loading" formElement="select" sortOrder="12">
            <settings>
                <dataType>text</dataType>
                <label translate="true">Image Attribute Loading</label>
                <dataScope>image_attribute_loading</dataScope>
                <notice translate="true">Place the value lazy on images that are below the fold on desktop for better page speed performance.</notice>
            </settings>
            <formElements>
                <select>
                    <settings>
                        <options>
                            <option name="eager" xsi:type="array">
                                <item name="value" xsi:type="string">eager</item>
                                <item name="label" xsi:type="string">eager</item>
                            </option>
                            <option name="lazy" xsi:type="array">
                                <item name="value" xsi:type="string">lazy</item>
                                <item name="label" xsi:type="string">lazy</item>
                            </option>
                        </options>
                        <caption translate="true">Select the correct loading method for the image.</caption>
                    </settings>
                </select>
            </formElements>
        </field>`
`        <field name="mobile_image_attribute_loading" formElement="select" sortOrder="15">
            <settings>
                <dataType>text</dataType>
                <label translate="true">Mobile Image Attribute Loading</label>
                <dataScope>mobile_image_attribute_loading</dataScope>
                <notice translate="true">Place the value lazy on images that are below the fold on mobile for better page speed performance.</notice>
            </settings>
            <formElements>
                <select>
                    <settings>
                        <options>
                            <option name="eager" xsi:type="array">
                                <item name="value" xsi:type="string">eager</item>
                                <item name="label" xsi:type="string">eager</item>
                            </option>
                            <option name="lazy" xsi:type="array">
                                <item name="value" xsi:type="string">lazy</item>
                                <item name="label" xsi:type="string">lazy</item>
                            </option>
                        </options>
                        <caption translate="true">Select the correct loading method for the image.</caption>
                    </settings>
                </select>
            </formElements>
        </field>`
        
image.xml
`                        <attribute name="image_attribute_loading" source="loading"/>
                        <attribute name="mobile_image_attribute_loading" source="loading"/>`

ImageData.xml
`    
    <entity name="PageBuilderImageLoadingProperty" type="pagebuilder_Loading_property">
        <data key="name">Loading</data>
        <data key="section">general</data>
        <data key="fieldName">image_attribute_loading</data>
        <data key="value">eager</data>
    </entity>`

`    
    <entity name="PageBuilderImageLoadingProperty" type="pagebuilder_Loading_property">
        <data key="name">Loading</data>
        <data key="section">general</data>
        <data key="fieldName">mobile_image_attribute_loading</data>
        <data key="value">eager</data>
    </entity>`

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aj-prajapati,

Thanks for the contribution!

Please look into the automated test failures.

Thanks

**Comment by engcom-Hotel** [comment]
We are picking this PR for further development

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by larsmbm** [comment]
Hello @engcom-Hotel,

Great that this issue is picked up for further development :)
I do question will the lazy loading attribute option be added as wel? 
Like my comment suggest in this ticket earlier.

Thank you in advance.

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Performance Acceptance Tests, Semantic Version Checker, Unit Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests, WebAPI Tests, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Performance Acceptance Tests, Semantic Version Checker, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Functional Tests B2B, Functional Tests EE, Magento Health Index, Semantic Version Checker

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Performance Acceptance Tests, Semantic Version Checker, Unit Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Performance Acceptance Tests, Semantic Version Checker, Unit Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
It seems the bot moved it to `Changes Requested`, moving back to `Pending Review`

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
Hi @aj-prajapati,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Content>>Pages>>Content>>Edit with Pagebuilder
- Add Row>>Add Image element.
- Upload images for both desktop image and Mobile image
- Check both images are having Width and Height.




**Before:** :heavy_multiplication_x: 


Screenshot 2024-05-08 at 12 20 44





**After:** :heavy_check_mark:  




New-Pages-Elements-Content-Magento-Admin





Screenshot 2024-05-08 at 14 40 52



Screenshot 2024-05-08 at 14 41 44




Builds are failed. Hence, moving this PR to **Extended Testing.**

Thanks.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Pull request merged**
