### PR TITLE
Change to the new slick version 1.9.0

### PR DESCRIPTION
**Pull request by in-session**
### Fixed Issues (if relevant)

1. magento/magento2-page-builder#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by paras89** [comment]
@in-session can you merge develop branch into your fork branch and push so we can process this PR? Thanks!

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@paras89 as requested even though i honestly don't support slick slider at all and it would be time to say goodbye to it. 
Also regarding https://github.com/magento/magento2/issues/34595. Here, restructuring to Swiper would make much more sense, but unfortunately a common problem

**Comment by in-session** [comment]
@magento run Unit Tests

**Comment by Januszpl** [comment]
@in-session it should be reverted to 1.8.1 because
https://github.com/kenwheeler/slick/issues/3477#issuecomment-511957967

**Pull request merged**
