### PR TITLE
Fix issue #730, pagebuilder breaks clean install

### PR DESCRIPTION
**Pull request by hardyjohnson**
### Description (*)

This is described by @lbajsarowicz in #730, test extension attribute object has a valid method prior to use in the plugin. Failure to do so will result in a fatal error: uncaught error: call to undefined method during Magento installation on a clean database. This is a PR implementing the recommended patch by @lbajsarowicz which I have tested locally after writing a very similar patch. I am opening this PR as it is an itch I need scratched. Thanks and credit to you Lucasz.

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#730: Magento PageBuilder causes failure during clean install

### Manual testing scenarios (*)

Run `bin/magento setup:install` with the `--clean-database` flag set.

### Checklist
 - [] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run all tests

**Comment by hardyjohnson** [comment]
@magento run Tests EE

**Comment by hardyjohnson** [comment]
@magento run Tests EE

**Comment by hardyjohnson** [comment]
@magento run all tests

**Comment by hardyjohnson** [comment]
@magento run all tests

**Comment by paras89** [comment]
Hello @hardyjohnson, can you pull develop branch from main into your fork branch and push. We can then try to get all the tests green to merge this request. Thanks!

**Comment by hardyjohnson** [comment]
@paras89 I will see what I can do this afternoon, thank you.

**Comment by hardyjohnson** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run Functional Tests EE

**Comment by hardyjohnson** [comment]
@paras89 thank you for getting this through the testing phase

**Pull request merged**
