### PR TITLE
fix container width for description inside the catalog product view

### PR DESCRIPTION
**Pull request by PierW**
### Description (*)

When I insert the description of the product I have this problem:

Schermata 2022-02-19 alle 20 35 38

**It's not aligned**

**FIX:**
Schermata 2022-02-19 alle 20 39 30

Schermata 2022-02-19 alle 20 40 58

Schermata 2022-02-19 alle 20 37 09

**The text should be aligned**

### Bug

* [#801](https://github.com/magento/magento2-page-builder/issues/801) fix the container for description inserted with page builder inside catalog product view
* [#35123](https://github.com/magento/magento2/issues/35123) fix the container for description inserted with page builder inside catalog product view

### Fixed Issues (if relevant)

1. magento/magento2-page-builder#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Magento 2.4.3-p1
2. Module Page Builder Enabled (Default)
3. Design Page - Template Product full width (Default with page builder enabled)
4. Enter to the backoffice
5. Create a Product and insert a description with page builder inside a row and 1 column
6. Save

### Checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by PierW** [comment]
https://github.com/magento run all tests

**Comment by paras89** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests, Unit Tests, WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @PierW,

Please merge this PR branch with the latest develop branch, after that we can pick this PR for review.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
PR Changes seems good to me, hence approving this PR.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop test instance

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @PierW,


Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

- Module Page Builder Enabled (Default)
- Design Page - Template Product full width (Default with page builder enabled)
- Enter to the backoffice
- Create a Product and insert a description with page builder inside a row and 1 column
- Save


**Before:** :heavy_multiplication_x: 


Screenshot from 2024-02-29 13-19-23



**After:** :heavy_check_mark:  



Screenshot from 2024-02-29 13-48-27



Thanks.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Performance Acceptance Tests, Static Tests, Unit Tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests CE, Integration Tests, Static Tests, WebAPI Tests

**Comment by engcom-November** [comment]
@magento run Static Tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-November** [comment]
@magento run WebAPI Tests

**Comment by engcom-November** [comment]
The WebAPI failures on consecutive runs are different, and are flaky.

**1st Run**
image

**2nd Run**
image

Hence moving this pr for further processing.

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Comment by TuVanDev** [comment]
@engcom-Hotel do you think it's better to use shorthand in this case? If so, could you make the following changes?
Current code:
```
padding-left: 15px;
padding-right: 15px;
```
Proposed change:
```
padding: 0 15px;
```

**Comment by engcom-Hotel** [comment]
Sure @TuVanDev, Please make the change. We will then proceed with this PR.

Till then moving PR to `Changes Requested`

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by TuVanDev** [comment]
I don't have permission to make the changes. Thanks to @engcom-Hotel for the changes.

**Comment by engcom-Bravo** [comment]
Hi @PierW,

Thanks for your Contribution!!.

We have verified the issue in Latest 2.4-develop instance and we are not able to reproduce the issue.Kindly refer the screenshots.


Nadia-Elements-Shell-09-26-2024_11_42_AM

Screenshot 2024-09-26 at 11 41 46


Could you please let us know if we are missing anything here.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @PierW,

Thank you for your contribution!

As mentioned here https://github.com/magento/magento2-page-builder/pull/802#issuecomment-2376078694, please have a look and let us know if we are missing anything.

Till then closing this PR. Please feel free to reopen it as you want to update further.

Thank you!

**Pull request closed without merging**
