### PR TITLE
magento/magento2-page-builder#842: Template Preview Images Incorrectly Saved to Media Directory

### PR DESCRIPTION
**Pull request by bluemwhitew**
### Description (*)

This fixes an issue where Page Builder would save its preview images into the top-level `media` directory, as opposed to within its designated `.template-manager` subdirectory. It also contains some minor refactoring.

### Story

_N/A_

### Bug

_N/A_

### Task

_N/A_

### Fixed Issues

1. magento/magento2-page-builder#842: Template Preview Images Incorrectly Saved to Media Directory

### Builds

_N/A_

### Related Pull Requests

_N/A_

### Manual Testing Scenarios (*)

- [ ] Validate Saved to Directory

1. Click on _any_ Page Builder-enabled field (doesn't have to be empty)
2. Click **Save as Template**
3. Define a Template Name (such as "Example")
4. Click **Save**
5. Verify that "The current contents of Page Builder has been successfully saved as a template."
6. Click **Apply Template**
7. Inspect the Preview Image path (can be full-size _or_ thumbnail) of the template you just saved
8. Validate that the image was saved _within_ the `.template-manager` directory

- [ ] Validate Deleted from Directory

1. Follow Steps 1-8 from the "Validate Saved to Directory" scenario
2. Browse to **Content** » **Templates**
3. Open the Preview Image in a new tab ("Open Image in New Tab")
4. Click **Delete**
5. Verify that you see, "Are you sure you want to permanently delete template Example" (_where "Example" is your Template Name_)
6. Click **OK**
7. Verify that you see, "Template successfully deleted."
8. Reload the tab from Step 3 pointing to the Preview Image
9. Validate that it now returns a 404

### Questions or Comments

Other minor improvements that can be made here include:

- amending the messaging from "The current contents of Page Builder **has** been successfully saved as a template." to "The current contents of Page Builder **have** been successfully saved as a template."
- reducing the complexity of the `storePreviewImage` method by creating helper methods which handle image naming conventions, etc.
- improving instances of `str_replace('.jpg', '-thumb.jpg', ...)` so that other file formats (such as PNG) can be used, particularly via data patches.

### Checklist
- [x] Pull request has a meaningful description of its purpose
- [x] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
- [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bluemwhitew** [comment]
@magento run Integration Tests, Unit Tests

**Comment by bluemwhitew** [comment]
@magento run all tests

**Comment by bluemwhitew** [comment]
@magento run all tests

**Comment by bluemwhitew** [comment]
@dhaecker,

Sorry to ping directly, are these test failures already known (not related to this PR)? 🙏🏻

**Comment by dhaecker** [comment]
@bluemwhitew 
Hi,  long time no see!

Those failures are definitely not expected. Looking at the builds, branches being used, etc., I THINK the issue is that magento/magento2-page-builder/ is not synced with magento-commerce/magento2-page-builder/. Looks like the commits are 1 year behind so a LOT of stuff is missing (like php 8.2 compatibility & whatever else)... 
I'll ask around & see how this can be fixed

**Comment by dhaecker** [comment]
@magento run all tests

**Comment by dhaecker** [comment]
@bluemwhitew
i think i fixed the issue. magento/magento2-page-builder/develop was out of sync with magento-commerce/magento2-page-builder/develop. it is now in sync. however, you now need to merge in latest develop into your branch. once you do that, i THINK the builds should work

direct message me again if there are more problems (otherwise I might miss it)

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @bluemwhitew,

Thanks for the contribution!

The changes seems good to me, but please fix the static tests failures.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Enable PageBuilder

**Manual testing scenario:**
1. Click on _any_ Page Builder-enabled field (doesn't have to be empty)
2. Click **Save as Template**
3. Define a Template Name (such as "Example")
4. Click **Save**
5. Verify that "The current contents of Page Builder has been successfully saved as a template."
6. Click **Apply Template**
7. Inspect the Preview Image path (can be full-size _or_ thumbnail) of the template you just saved
8. Validate that the image was saved _within_ the `.template-manager` directory

**Before:** :heavy_multiplication_x:

image
image

**Actual Result:** :heavy_check_mark:
Image(s) should stored under `~/pub/media/.template-manager/`

**After:** :heavy_check_mark: 
image
image

**Tested all the manual scenarios, no impact on regression testing.**

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by bluemwhitew** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
Moving the PR in `Merge in progress`

**Review by engcom-Hotel — APPROVED** [review]

**Comment by bluemwhitew** [comment]
Thank you so much! 🙏🏻

**Pull request merged**
