### PR TITLE
Ignore styles which no longer apply

### LINKED ISSUE #863: [Issue] Ignore styles which no longer apply
This issue is automatically created based on existing pull request: magento/magento2-page-builder#804: Ignore styles which no longer apply

---------
### Description
When PageBuilder initialises, it moves styles from a <style> tag into `data-{viewport}-styles` attributes. If there are CSS selectors that do not match any elements, an error is thrown:

Screenshot_2022-03-02_11-17-34

This pull request fixes this bug.

### Manual testing scenarios
1. Use Magento import tool to set a product description (or other Page Builder-enabled attribute) which contains HTML, including some CSS that does not match any elements. (eg, `<span>Sample text</span><style>#not-found { color: red; }</style>`)
1. Navigate to this product in the admin.
1. Witness that Page Builder fails to initialise for this field, and saving the product is impossible (due to a different JavaScript error which stems from the same root cause).
1. Apply the changes in this pull request.
1. Witness that Page Builder initialises as expected, and it is possible to save the product.

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
When PageBuilder initialises, it moves styles from a <style> tag into `data-{viewport}-styles` attributes. If there are CSS selectors that do not match any elements, an error is thrown:

Screenshot_2022-03-02_11-17-34

This pull request fixes this bug.

### Manual testing scenarios
1. Use Magento import tool to set a product description (or other Page Builder-enabled attribute) which contains HTML, including some CSS that does not match any elements. (eg, `<span>Sample text</span><style>#not-found { color: red; }</style>`)
1. Navigate to this product in the admin.
1. Witness that Page Builder fails to initialise for this field, and saving the product is impossible (due to a different JavaScript error which stems from the same root cause).
1. Apply the changes in this pull request.
1. Witness that Page Builder initialises as expected, and it is possible to save the product.

### Checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2-page-builder#863: Ignore styles which no longer apply

### CODE REVIEW

**Comment by paras89** [comment]
@magento run all tests

**Comment by paras89** [comment]
@fredden - can you pull develop branch into your fork's branch and fix a failing static test? After that we should be good to merge this PR!

**Comment by fredden** [comment]
@magento run all tests

**Comment by paras89** [comment]
@magento run Functional Tests B2B

**Comment by paras89** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @fredden,

Thanks for the contribution!

The changes look good to me, hence approving the PR.

Thanks

**Comment by engcom-Bravo** [comment]
Hi @fredden,

Thanks for the collaboration & contribution!.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Manual testing scenarios**

- Use Magento import tool to set a product description (or other Page Builder-enabled attribute) which contains HTML, including some CSS that does not match any elements. (eg, <span>Sample text</span><style>#not-found { color: red; }</style>)
- Navigate to this product in the admin.
- Witness that Page Builder fails to initialise for this field, and saving the product is impossible (due to a different JavaScript error which stems from the same root cause).




https://github.com/user-attachments/assets/ae9d8699-b3d0-402c-8953-627ee6d1649d



After importing the product with the description we are able to save the product successfully.

Could you please try to reproduce the issue in Latest 2.4-develop instance and could you please let us know if we are still missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @fredden,

Thank you for your contribution!

As mentioned here https://github.com/magento/magento2-page-builder/pull/804#issuecomment-2250045772, please have a look and let us know if we are missing anything.

Till then closing this PR. Please feel free to reopen it as you want to update further.

Thank you!

**Pull request closed without merging**
